export const Scope = {
  PRISMA_SERVICE: 'PRISMA_SERVICE',
  EXTERNAL_ARTICLE_SERVICE: 'EXTERNAL_ARTICLE_SERVICE',
  ARTICLE_SERVICE: 'ARTICLE_SERVICE',
  AUTOFILL_ARTICLE_USECASE: 'AUTOFILL_ARTICLE_USECASE',
};
