name: Frontend CI
 
on:
  push:
    branches: ["master"]
    paths-ignore:
      - "backend/**"

  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - "backend/**"
  
jobs:
  build:
      name: Build and Test
      timeout-minutes: 15
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: './frontend'

      steps:
        - name: Check out code
          uses: actions/checkout@v3
          with:
            fetch-depth: 2
 
        - name: Setup Node.js environment
          uses: actions/setup-node@v3
          with:
            node-version: 16
            cache: 'yarn'
            cache-dependency-path: ./frontend/yarn.lock

        - name: Install dependencies
          run: yarn

        - name: Type-Check and Lint
          run: yarn validate